#ifndef STRUCTS_H
#define STRUCTS_H

struct abstract_declarator;
struct alignment_specifier;
struct assignment_expression;
struct atomic_type_specifier;
struct block_item;
struct block_item_list;
struct compound_statement;
struct constant_expression;
struct declaration;
struct declaration_list;
struct declaration_specifiers;
struct declarator;
struct designation;
struct designator;
struct designator_list;
struct direct_declarator;
struct enumerator;
struct enumerator_list;
struct enum_specifier;
struct expression;
struct expression_statement;
struct external_declaration;
struct function_definition;
struct function_specifier;
struct identifier_list;
struct init_declarator_list;
struct init_declarator;
struct initializer;
struct initializer_list;
struct jump_statement;
struct labeled_statement;
struct parameter_declaration;
struct parameter_list;
struct parameter_type_list;
struct pointer;
struct selection_statement;
struct specifier_qualifier_list;
struct statement;
struct static_assert_declaration;
struct storage_class_specifier;
struct struct_declaration_list;
struct struct_declaration;
struct struct_declarator_list;
struct struct_declarator;
struct struct_or_union;
struct struct_or_union_specifier;
struct translation_unit;
struct type_name;
struct type_qualifier;
struct type_qualifier_list;
struct type_specifier;

#endif
